<?php
function beauty_preprocess(&$variables, $hook) {
  $variables['base_path'] = base_path();
}

function beauty_form_views_exposed_form_alter(&$form, &$form_state) {
  if($form["#id"] == 'views-exposed-form-popular-genre-popular-genre-view') {
    $form['genre']['#options']["All"] = 'All Genres';
   }
}

function beauty_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'search_block_form') {
    $form['keys']['#attributes']['placeholder'] = 'Search book';
  }
}
